name = "dmsfinder-vonbusch"
main = "worker.js"
compatibility_date = "2026-01-01"
compatibility_flags = ["nodejs_compat"]

account_id = "6d2a1d5945f8b63047a1d59a9f94de21"

[assets]
directory = "."
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "dms-finder-db-eu"
database_id = "c03ae94f-d319-45ce-a461-a85f25ea86a8"

[[send_email]]
name = "SEND_EMAIL"
